services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    command: [ "sh", "./wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: django_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: django_pass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
